[package]
name = "noise-wasm"
version = "0.1.0"
authors = ["Brian Craig <briancraigok@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "wee_alloc"]

[dependencies]
wasm-bindgen = "0.2.63"
noise-protocol = "0.1.3"
wee_alloc = { version = "0.4.5", optional = true }
console_error_panic_hook = { version = "0.1.6", optional = true }
getrandom = { version = "0.2", features = ["js"] }

[dependencies.noise-rust-crypto]
version = "0.4.1"
default-features = false
features = ["use-sha2", "use-chacha20poly1305", "use-x25519"]


[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
